import Header from './Component/Header'
import Footer from './Component/Footer';
import './globals.css'
import Container from './Component/Container';
import { Ubuntu,Shadows_Into_Light } from 'next/font/google'

const ubuntu = Ubuntu ({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
      <Container>
          <Header/>
          {children}
          <Footer/>
        </Container>
      </body>
    </html>
  )
}
